import type { Lease } from "./types"

/**
 * Sample portfolio for the prototype.
 * 32 leases across 5 property types and 12 sub-markets, with realistic comp counts and variances.
 * In production this would come from the portfolio database.
 */
export const SAMPLE_LEASES: Lease[] = [
  // --- Office ---
  {
    id: "L-001",
    address: "432 Park Avenue, Floor 28",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    sf: 12500,
    currentRentPsf: 92.5,
    marketRentPsf: 84.2,
    marketCompCount: 14,
    marketConfidence: "high",
    expiryDate: "2027-03-15",
  },
  {
    id: "L-002",
    address: "525 Lexington Avenue, Floor 14",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    sf: 8200,
    currentRentPsf: 88.0,
    marketRentPsf: 81.5,
    marketCompCount: 12,
    marketConfidence: "high",
    expiryDate: "2026-09-30",
  },
  {
    id: "L-003",
    address: "200 West Street, Floor 9",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Downtown",
    city: "New York",
    state: "NY",
    sf: 18400,
    currentRentPsf: 76.5,
    marketRentPsf: 78.9,
    marketCompCount: 9,
    marketConfidence: "medium",
    expiryDate: "2028-06-01",
  },
  {
    id: "L-004",
    address: "55 Water Street, Floor 22",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Downtown",
    city: "New York",
    state: "NY",
    sf: 24000,
    currentRentPsf: 71.0,
    marketRentPsf: 76.2,
    marketCompCount: 11,
    marketConfidence: "high",
    expiryDate: "2025-12-31",
  },
  {
    id: "L-005",
    address: "1 Bryant Park, Floor 31",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    sf: 6800,
    currentRentPsf: 102.0,
    marketRentPsf: 95.8,
    marketCompCount: 8,
    marketConfidence: "medium",
    expiryDate: "2026-04-30",
  },
  {
    id: "L-006",
    address: "350 Fifth Avenue, Floor 56",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    sf: 15200,
    currentRentPsf: 79.0,
    marketRentPsf: null,
    marketCompCount: 0,
    marketConfidence: "low",
    expiryDate: "2029-01-15",
  },
  {
    id: "L-007",
    address: "1 Federal Street, Floor 18",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Back Bay",
    city: "Boston",
    state: "MA",
    sf: 9500,
    currentRentPsf: 68.5,
    marketRentPsf: 71.4,
    marketCompCount: 10,
    marketConfidence: "high",
    expiryDate: "2027-08-31",
  },
  {
    id: "L-008",
    address: "100 Seaport Boulevard, Floor 6",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Seaport",
    city: "Boston",
    state: "MA",
    sf: 14200,
    currentRentPsf: 74.0,
    marketRentPsf: 70.1,
    marketCompCount: 7,
    marketConfidence: "medium",
    expiryDate: "2026-11-30",
  },
  {
    id: "L-009",
    address: "300 South Wacker Drive, Floor 12",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Loop",
    city: "Chicago",
    state: "IL",
    sf: 11000,
    currentRentPsf: 42.0,
    marketRentPsf: 44.8,
    marketCompCount: 13,
    marketConfidence: "high",
    expiryDate: "2027-05-31",
  },
  {
    id: "L-010",
    address: "200 South Michigan Avenue",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Loop",
    city: "Chicago",
    state: "IL",
    sf: 7500,
    currentRentPsf: 47.5,
    marketRentPsf: 43.9,
    marketCompCount: 9,
    marketConfidence: "medium",
    expiryDate: "2025-10-15",
  },
  {
    id: "L-011",
    address: "888 South Figueroa Street",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Downtown LA",
    city: "Los Angeles",
    state: "CA",
    sf: 16800,
    currentRentPsf: 52.0,
    marketRentPsf: 49.3,
    marketCompCount: 11,
    marketConfidence: "high",
    expiryDate: "2026-07-31",
  },
  {
    id: "L-012",
    address: "1 Sansome Street, Floor 24",
    tenant: "Halberd Capital",
    propertyType: "Office",
    submarket: "Financial District",
    city: "San Francisco",
    state: "CA",
    sf: 9800,
    currentRentPsf: 81.0,
    marketRentPsf: 75.6,
    marketCompCount: 6,
    marketConfidence: "medium",
    expiryDate: "2027-02-28",
  },

  // --- Industrial ---
  {
    id: "L-013",
    address: "2400 Cherry Industrial Circle",
    tenant: "Halberd Logistics",
    propertyType: "Industrial",
    submarket: "Inland Empire",
    city: "Los Angeles",
    state: "CA",
    sf: 220000,
    currentRentPsf: 12.4,
    marketRentPsf: 14.8,
    marketCompCount: 16,
    marketConfidence: "high",
    expiryDate: "2028-03-31",
  },
  {
    id: "L-014",
    address: "1800 Logistics Drive",
    tenant: "Halberd Logistics",
    propertyType: "Industrial",
    submarket: "Inland Empire",
    city: "Los Angeles",
    state: "CA",
    sf: 185000,
    currentRentPsf: 11.8,
    marketRentPsf: 14.2,
    marketCompCount: 14,
    marketConfidence: "high",
    expiryDate: "2026-12-31",
  },
  {
    id: "L-015",
    address: "501 Cargo Way",
    tenant: "Halberd Logistics",
    propertyType: "Industrial",
    submarket: "Port District",
    city: "Newark",
    state: "NJ",
    sf: 145000,
    currentRentPsf: 16.2,
    marketRentPsf: 15.4,
    marketCompCount: 12,
    marketConfidence: "high",
    expiryDate: "2027-06-30",
  },
  {
    id: "L-016",
    address: "2200 Distribution Parkway",
    tenant: "Halberd Logistics",
    propertyType: "Industrial",
    submarket: "Port District",
    city: "Newark",
    state: "NJ",
    sf: 95000,
    currentRentPsf: 17.5,
    marketRentPsf: 15.9,
    marketCompCount: 10,
    marketConfidence: "medium",
    expiryDate: "2025-08-15",
  },
  {
    id: "L-017",
    address: "888 Industrial Boulevard",
    tenant: "Halberd Logistics",
    propertyType: "Industrial",
    submarket: "DFW Airport",
    city: "Dallas",
    state: "TX",
    sf: 310000,
    currentRentPsf: 8.4,
    marketRentPsf: 9.1,
    marketCompCount: 18,
    marketConfidence: "high",
    expiryDate: "2029-03-31",
  },
  {
    id: "L-018",
    address: "1200 Freight Lane",
    tenant: "Halberd Logistics",
    propertyType: "Industrial",
    submarket: "DFW Airport",
    city: "Dallas",
    state: "TX",
    sf: 165000,
    currentRentPsf: 9.2,
    marketRentPsf: null,
    marketCompCount: 0,
    marketConfidence: "low",
    expiryDate: "2027-11-30",
  },

  // --- Retail ---
  {
    id: "L-019",
    address: "568 Broadway",
    tenant: "Halberd Retail Co",
    propertyType: "Retail",
    submarket: "SoHo",
    city: "New York",
    state: "NY",
    sf: 4200,
    currentRentPsf: 285.0,
    marketRentPsf: 312.0,
    marketCompCount: 8,
    marketConfidence: "high",
    expiryDate: "2026-05-31",
  },
  {
    id: "L-020",
    address: "725 Fifth Avenue",
    tenant: "Halberd Retail Co",
    propertyType: "Retail",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    sf: 2800,
    currentRentPsf: 1850.0,
    marketRentPsf: 1620.0,
    marketCompCount: 5,
    marketConfidence: "medium",
    expiryDate: "2025-09-30",
  },
  {
    id: "L-021",
    address: "Rodeo Drive 240",
    tenant: "Halberd Retail Co",
    propertyType: "Retail",
    submarket: "Beverly Hills",
    city: "Los Angeles",
    state: "CA",
    sf: 3500,
    currentRentPsf: 925.0,
    marketRentPsf: 880.0,
    marketCompCount: 6,
    marketConfidence: "medium",
    expiryDate: "2027-04-30",
  },
  {
    id: "L-022",
    address: "Magnificent Mile 600",
    tenant: "Halberd Retail Co",
    propertyType: "Retail",
    submarket: "Mag Mile",
    city: "Chicago",
    state: "IL",
    sf: 5100,
    currentRentPsf: 195.0,
    marketRentPsf: 218.0,
    marketCompCount: 9,
    marketConfidence: "high",
    expiryDate: "2026-10-31",
  },
  {
    id: "L-023",
    address: "Newbury Street 145",
    tenant: "Halberd Retail Co",
    propertyType: "Retail",
    submarket: "Back Bay",
    city: "Boston",
    state: "MA",
    sf: 2400,
    currentRentPsf: 162.0,
    marketRentPsf: 148.0,
    marketCompCount: 7,
    marketConfidence: "medium",
    expiryDate: "2028-02-28",
  },

  // --- Multifamily ---
  {
    id: "L-024",
    address: "The Set, 200 Bridge Street",
    tenant: "Halberd Residential",
    propertyType: "Multifamily",
    submarket: "DUMBO",
    city: "Brooklyn",
    state: "NY",
    sf: 285000,
    currentRentPsf: 68.0,
    marketRentPsf: 72.5,
    marketCompCount: 11,
    marketConfidence: "high",
    expiryDate: "2030-06-30",
  },
  {
    id: "L-025",
    address: "The Williamsburg, 60 N 5th",
    tenant: "Halberd Residential",
    propertyType: "Multifamily",
    submarket: "Williamsburg",
    city: "Brooklyn",
    state: "NY",
    sf: 198000,
    currentRentPsf: 64.5,
    marketRentPsf: 67.8,
    marketCompCount: 9,
    marketConfidence: "medium",
    expiryDate: "2029-09-30",
  },
  {
    id: "L-026",
    address: "Skyline Tower, 300 W Olympic",
    tenant: "Halberd Residential",
    propertyType: "Multifamily",
    submarket: "Downtown LA",
    city: "Los Angeles",
    state: "CA",
    sf: 412000,
    currentRentPsf: 48.2,
    marketRentPsf: 45.6,
    marketCompCount: 13,
    marketConfidence: "high",
    expiryDate: "2031-03-31",
  },
  {
    id: "L-027",
    address: "Riverwalk Lofts, 1200 Wabash",
    tenant: "Halberd Residential",
    propertyType: "Multifamily",
    submarket: "Loop",
    city: "Chicago",
    state: "IL",
    sf: 245000,
    currentRentPsf: 36.5,
    marketRentPsf: 38.4,
    marketCompCount: 10,
    marketConfidence: "high",
    expiryDate: "2028-12-31",
  },

  // --- Mixed-Use ---
  {
    id: "L-028",
    address: "Hudson Yards Block 5",
    tenant: "Halberd Capital",
    propertyType: "Mixed-Use",
    submarket: "Hudson Yards",
    city: "New York",
    state: "NY",
    sf: 88000,
    currentRentPsf: 105.0,
    marketRentPsf: 98.5,
    marketCompCount: 6,
    marketConfidence: "medium",
    expiryDate: "2032-01-31",
  },
  {
    id: "L-029",
    address: "Domain Northside, Building 12",
    tenant: "Halberd Capital",
    propertyType: "Mixed-Use",
    submarket: "North Austin",
    city: "Austin",
    state: "TX",
    sf: 64000,
    currentRentPsf: 38.0,
    marketRentPsf: 41.2,
    marketCompCount: 8,
    marketConfidence: "medium",
    expiryDate: "2027-07-31",
  },
  {
    id: "L-030",
    address: "Ponce City Market, Suite 240",
    tenant: "Halberd Capital",
    propertyType: "Mixed-Use",
    submarket: "Old Fourth Ward",
    city: "Atlanta",
    state: "GA",
    sf: 32000,
    currentRentPsf: 44.5,
    marketRentPsf: 46.2,
    marketCompCount: 5,
    marketConfidence: "medium",
    expiryDate: "2026-08-31",
  },
  {
    id: "L-031",
    address: "Easton Town Center, Phase 4",
    tenant: "Halberd Capital",
    propertyType: "Mixed-Use",
    submarket: "Easton",
    city: "Columbus",
    state: "OH",
    sf: 41000,
    currentRentPsf: 28.0,
    marketRentPsf: null,
    marketCompCount: 0,
    marketConfidence: "low",
    expiryDate: "2028-05-31",
  },
  {
    id: "L-032",
    address: "Mission Bay 1500",
    tenant: "Halberd Capital",
    propertyType: "Mixed-Use",
    submarket: "Mission Bay",
    city: "San Francisco",
    state: "CA",
    sf: 76000,
    currentRentPsf: 82.0,
    marketRentPsf: 78.4,
    marketCompCount: 7,
    marketConfidence: "medium",
    expiryDate: "2029-02-28",
  },
]
