import type { Lease } from "./types"

/**
 * Sample portfolio for the prototype.
 * 32 leases across 5 property types and 14 sub-markets in 10 cities, with realistic comp counts and variances.
 * Each lease has approximate lng/lat for map plotting.
 * In production this would come from the portfolio database.
 */
export const SAMPLE_LEASES: Lease[] = [
  // --- New York Office ---
  {
    id: "L-001",
    address: "10 High Street",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    lng: -73.9772,
    lat: 40.7589,
    sf: 12500,
    currentRentPsf: 78.4,
    marketRentPsf: 47.2,
    marketCompCount: 24,
    marketConfidence: "high",
    expiryDate: "2027-01-15",
  },
  {
    id: "L-002",
    address: "525 Lexington Avenue, Floor 14",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Midtown",
    city: "New York",
    state: "NY",
    lng: -73.9742,
    lat: 40.7558,
    sf: 8200,
    currentRentPsf: 88.0,
    marketRentPsf: 62.5,
    marketCompCount: 18,
    marketConfidence: "high",
    expiryDate: "2026-09-30",
  },
  {
    id: "L-003",
    address: "200 West Street, Floor 9",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Downtown",
    city: "New York",
    state: "NY",
    lng: -74.0145,
    lat: 40.7155,
    sf: 18400,
    currentRentPsf: 56.5,
    marketRentPsf: 64.9,
    marketCompCount: 16,
    marketConfidence: "high",
    expiryDate: "2028-06-01",
  },
  {
    id: "L-004",
    address: "55 Water Street, Floor 22",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Downtown",
    city: "New York",
    state: "NY",
    lng: -74.009,
    lat: 40.7034,
    sf: 24000,
    currentRentPsf: 51.0,
    marketRentPsf: 62.2,
    marketCompCount: 11,
    marketConfidence: "high",
    expiryDate: "2025-12-31",
  },
  // --- Boston ---
  {
    id: "L-005",
    address: "One Exeter Plaza",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Back Bay",
    city: "Boston",
    state: "MA",
    lng: -71.0764,
    lat: 42.3503,
    sf: 9500,
    currentRentPsf: 62.1,
    marketRentPsf: 37.6,
    marketCompCount: 18,
    marketConfidence: "high",
    expiryDate: "2027-07-15",
  },
  {
    id: "L-006",
    address: "100 Seaport Boulevard, Floor 6",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Seaport",
    city: "Boston",
    state: "MA",
    lng: -71.0463,
    lat: 42.3519,
    sf: 14200,
    currentRentPsf: 64.0,
    marketRentPsf: 68.2,
    marketCompCount: 9,
    marketConfidence: "medium",
    expiryDate: "2026-11-30",
  },
  {
    id: "L-007",
    address: "772 Boylston Street",
    tenant: "Bosch",
    propertyType: "Retail",
    submarket: "Back Bay",
    city: "Boston",
    state: "MA",
    lng: -71.0822,
    lat: 42.3493,
    sf: 4200,
    currentRentPsf: 420.0,
    marketRentPsf: 700.0,
    marketCompCount: 12,
    marketConfidence: "high",
    expiryDate: "2029-04-30",
  },
  {
    id: "L-008",
    address: "ATM Beacon Street",
    tenant: "Bosch",
    propertyType: "Retail",
    submarket: "Beacon Hill",
    city: "Boston",
    state: "MA",
    lng: -71.0676,
    lat: 42.3588,
    sf: 1800,
    currentRentPsf: 192.0,
    marketRentPsf: 335.0,
    marketCompCount: 9,
    marketConfidence: "medium",
    expiryDate: "2028-05-31",
  },
  // --- Atlanta ---
  {
    id: "L-009",
    address: "Resurgens Plaza",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Buckhead",
    city: "Atlanta",
    state: "GA",
    lng: -84.3676,
    lat: 33.8484,
    sf: 22000,
    currentRentPsf: 34.8,
    marketRentPsf: 23.4,
    marketCompCount: 31,
    marketConfidence: "high",
    expiryDate: "2027-04-15",
  },
  {
    id: "L-010",
    address: "Buckhead Tower",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Buckhead",
    city: "Atlanta",
    state: "GA",
    lng: -84.3733,
    lat: 33.8439,
    sf: 16800,
    currentRentPsf: 32.4,
    marketRentPsf: 23.4,
    marketCompCount: 31,
    marketConfidence: "high",
    expiryDate: "2026-08-30",
  },
  {
    id: "L-011",
    address: "Midtown Atlanta Industrial Park",
    tenant: "Bosch",
    propertyType: "Industrial",
    submarket: "South Atlanta",
    city: "Atlanta",
    state: "GA",
    lng: -84.4099,
    lat: 33.6849,
    sf: 145000,
    currentRentPsf: 12.4,
    marketRentPsf: 14.8,
    marketCompCount: 22,
    marketConfidence: "high",
    expiryDate: "2030-01-31",
  },
  // --- Chicago ---
  {
    id: "L-012",
    address: "200 South Wacker Drive",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "West Loop",
    city: "Chicago",
    state: "IL",
    lng: -87.6371,
    lat: 41.8786,
    sf: 28500,
    currentRentPsf: 38.9,
    marketRentPsf: 42.3,
    marketCompCount: 31,
    marketConfidence: "high",
    expiryDate: "2028-03-15",
  },
  {
    id: "L-013",
    address: "Aon Center, Floor 41",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Loop",
    city: "Chicago",
    state: "IL",
    lng: -87.6213,
    lat: 41.8855,
    sf: 18200,
    currentRentPsf: 41.2,
    marketRentPsf: 39.8,
    marketCompCount: 28,
    marketConfidence: "high",
    expiryDate: "2027-09-30",
  },
  {
    id: "L-014",
    address: "Bensenville Distribution Center",
    tenant: "Bosch",
    propertyType: "Industrial",
    submarket: "O'Hare Submarket",
    city: "Chicago",
    state: "IL",
    lng: -87.9403,
    lat: 41.9554,
    sf: 220000,
    currentRentPsf: 8.6,
    marketRentPsf: 10.4,
    marketCompCount: 18,
    marketConfidence: "high",
    expiryDate: "2031-06-30",
  },
  // --- San Francisco / Bay Area ---
  {
    id: "L-015",
    address: "555 California Street, Floor 38",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Financial District",
    city: "San Francisco",
    state: "CA",
    lng: -122.4039,
    lat: 37.7929,
    sf: 16200,
    currentRentPsf: 88.2,
    marketRentPsf: 76.8,
    marketCompCount: 19,
    marketConfidence: "high",
    expiryDate: "2026-06-30",
  },
  {
    id: "L-016",
    address: "350 Mission Street, Floor 22",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "SoMa",
    city: "San Francisco",
    state: "CA",
    lng: -122.3961,
    lat: 37.7905,
    sf: 22400,
    currentRentPsf: 72.4,
    marketRentPsf: 78.2,
    marketCompCount: 14,
    marketConfidence: "high",
    expiryDate: "2028-11-30",
  },
  {
    id: "L-017",
    address: "Fremont Industrial Hub",
    tenant: "Bosch",
    propertyType: "Industrial",
    submarket: "East Bay",
    city: "San Francisco",
    state: "CA",
    lng: -121.9886,
    lat: 37.5485,
    sf: 185000,
    currentRentPsf: 18.4,
    marketRentPsf: 22.6,
    marketCompCount: 27,
    marketConfidence: "high",
    expiryDate: "2029-09-30",
  },
  // --- Los Angeles ---
  {
    id: "L-018",
    address: "Century City Plaza",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Century City",
    city: "Los Angeles",
    state: "CA",
    lng: -118.4179,
    lat: 34.0594,
    sf: 14800,
    currentRentPsf: 52.4,
    marketRentPsf: 58.6,
    marketCompCount: 22,
    marketConfidence: "high",
    expiryDate: "2027-12-15",
  },
  {
    id: "L-019",
    address: "Downtown LA Tower",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Downtown LA",
    city: "Los Angeles",
    state: "CA",
    lng: -118.2437,
    lat: 34.0522,
    sf: 19600,
    currentRentPsf: 38.4,
    marketRentPsf: 44.8,
    marketCompCount: 16,
    marketConfidence: "high",
    expiryDate: "2026-04-30",
  },
  // --- Dallas / Fort Worth ---
  {
    id: "L-020",
    address: "Uptown Dallas Tower",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Uptown",
    city: "Dallas",
    state: "TX",
    lng: -96.8021,
    lat: 32.8019,
    sf: 21400,
    currentRentPsf: 31.4,
    marketRentPsf: 28.9,
    marketCompCount: 8,
    marketConfidence: "medium",
    expiryDate: "2027-06-30",
  },
  {
    id: "L-021",
    address: "Dallas Logistics Park",
    tenant: "Bosch",
    propertyType: "Industrial",
    submarket: "South Dallas",
    city: "Dallas",
    state: "TX",
    lng: -96.7589,
    lat: 32.7137,
    sf: 280000,
    currentRentPsf: 6.2,
    marketRentPsf: 7.8,
    marketCompCount: 24,
    marketConfidence: "high",
    expiryDate: "2030-12-31",
  },
  // --- Florida ---
  {
    id: "L-022",
    address: "Boca Corporate Center I",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Boca Raton CBD",
    city: "Boca Raton",
    state: "FL",
    lng: -80.0831,
    lat: 26.3683,
    sf: 11200,
    currentRentPsf: 48.2,
    marketRentPsf: 29.3,
    marketCompCount: 6,
    marketConfidence: "medium",
    expiryDate: "2027-11-30",
  },
  {
    id: "L-023",
    address: "Naples Executive Suites",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Naples",
    city: "Naples",
    state: "FL",
    lng: -81.7948,
    lat: 26.1420,
    sf: 6400,
    currentRentPsf: 52.0,
    marketRentPsf: null,
    marketCompCount: 4,
    marketConfidence: "low",
    expiryDate: "2027-09-30",
  },
  {
    id: "L-024",
    address: "Miami Beach Retail",
    tenant: "Bosch",
    propertyType: "Retail",
    submarket: "South Beach",
    city: "Miami",
    state: "FL",
    lng: -80.1300,
    lat: 25.7826,
    sf: 3200,
    currentRentPsf: 184.0,
    marketRentPsf: 220.0,
    marketCompCount: 11,
    marketConfidence: "high",
    expiryDate: "2028-08-31",
  },
  // --- Philadelphia ---
  {
    id: "L-025",
    address: "ATM City Hall Plaza",
    tenant: "Bosch",
    propertyType: "Retail",
    submarket: "Center City",
    city: "Philadelphia",
    state: "PA",
    lng: -75.1635,
    lat: 39.9526,
    sf: 1900,
    currentRentPsf: 181.0,
    marketRentPsf: 360.0,
    marketCompCount: 14,
    marketConfidence: "high",
    expiryDate: "2028-09-30",
  },
  {
    id: "L-026",
    address: "Cira Centre, Floor 19",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "University City",
    city: "Philadelphia",
    state: "PA",
    lng: -75.1816,
    lat: 39.9558,
    sf: 13800,
    currentRentPsf: 38.4,
    marketRentPsf: 36.2,
    marketCompCount: 12,
    marketConfidence: "high",
    expiryDate: "2026-07-31",
  },
  // --- Seattle ---
  {
    id: "L-027",
    address: "Columbia Center, Floor 52",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Downtown Seattle",
    city: "Seattle",
    state: "WA",
    lng: -122.3301,
    lat: 47.6044,
    sf: 17200,
    currentRentPsf: 52.4,
    marketRentPsf: 44.2,
    marketCompCount: 18,
    marketConfidence: "high",
    expiryDate: "2027-03-31",
  },
  {
    id: "L-028",
    address: "Kent Distribution Hub",
    tenant: "Bosch",
    propertyType: "Industrial",
    submarket: "Kent Valley",
    city: "Seattle",
    state: "WA",
    lng: -122.2349,
    lat: 47.3809,
    sf: 165000,
    currentRentPsf: 11.8,
    marketRentPsf: 13.4,
    marketCompCount: 21,
    marketConfidence: "high",
    expiryDate: "2030-04-30",
  },
  // --- Washington DC / Mid-Atlantic ---
  {
    id: "L-029",
    address: "1101 K Street NW, Floor 8",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Downtown DC",
    city: "Washington",
    state: "DC",
    lng: -77.0276,
    lat: 38.9026,
    sf: 11400,
    currentRentPsf: 32.8,
    marketRentPsf: 41.6,
    marketCompCount: 24,
    marketConfidence: "high",
    expiryDate: "2028-02-28",
  },
  {
    id: "L-030",
    address: "Tysons Corner Office",
    tenant: "Bosch",
    propertyType: "Office",
    submarket: "Tysons",
    city: "McLean",
    state: "VA",
    lng: -77.2294,
    lat: 38.9187,
    sf: 9800,
    currentRentPsf: 36.2,
    marketRentPsf: 42.4,
    marketCompCount: 19,
    marketConfidence: "high",
    expiryDate: "2027-10-31",
  },
  // --- Mixed-Use / Multifamily ---
  {
    id: "L-031",
    address: "The Martin · Mixed-Use",
    tenant: "Bosch",
    propertyType: "Mixed-Use",
    submarket: "South Lake Union",
    city: "Seattle",
    state: "WA",
    lng: -122.3358,
    lat: 47.6253,
    sf: 8400,
    currentRentPsf: 64.5,
    marketRentPsf: 58.2,
    marketCompCount: 7,
    marketConfidence: "medium",
    expiryDate: "2026-12-31",
  },
  {
    id: "L-032",
    address: "Hudson Yards Residence",
    tenant: "Bosch",
    propertyType: "Multifamily",
    submarket: "Hudson Yards",
    city: "New York",
    state: "NY",
    lng: -74.0021,
    lat: 40.7536,
    sf: 32000,
    currentRentPsf: 88.5,
    marketRentPsf: 92.8,
    marketCompCount: 11,
    marketConfidence: "high",
    expiryDate: "2029-06-30",
  },
]
